all:
	if [ ! -d ../../lib/include ] ; then mkdir -p ../../lib/include/; fi
	cp ./include/singleton.h ../../lib/include/
	cp ./include/dbg_print.h ../../lib/include/
	cp ./include/iterator_T.h ../../lib/include/
	cp ./include/refCountPointer.h ../../lib/include/
